language: java
jdk:
  - openjdk8

jods:
  include:
    -language: node_js
    node_js: 12
    before_script:
      - "npm install --prefix ./src/main/frontend/"
      - "npm run build --prefix ./src/main/frontend/"

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
    - "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
email:
  recipients:
    - jssongjk637@gmail.com